name: shadex
description: "A customizable Flutter widget that adds soft, blurred shadow effects to any child widget."
version: 0.0.1
homepage: https://github.com/Munsif-Ali/shadex.git

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
